name:               typed-state-machine
version:            0.1.0.0
author:             Marco Perone
maintainer:         marco.perone@tweag.io
copyright:          2022 Tweag I/O
license:            OtherLicense
extra-source-files:
  - README.md

ghc-options:
  -W
  -Wall
  -Werror
  -fwrite-ide-info
  -hiedir=.hie

library:
  source-dirs:      src

dependencies:
  - base >= 4.14 && < 5
  - profunctors
  - singletons
  - singletons-base
  - text

tests:
  typed-state-machine-spec:
    main:           Spec.hs
    source-dirs:    spec
    dependencies:
      - typed-state-machine
      - hspec
      - text
